jobs:
  deploy-container:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install

      # Build the container
      - name: Build container
        run: pnpm run build

      # Configure AWS credentials using official GitHub Action
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: your-aws-region # Replace with your AWS region, e.g., 'us-west-2'

      # Deploy the container to S3 bucket
      - name: Deploy to S3
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
