name: deploy-container
# Trying to learn how to deploy a container to S3 bucket
# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - main
    # Only run workflow for changes in the container directory
    paths:
      - 'packages/container/**'

# Set the working directory for all run steps to inside of container directory
defaults:
  run:
    working-directory: packages/container

# Define jobs for the workflow
jobs:
  deploy-container:
    runs-on: ubuntu-latest

    # Define steps for the job
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

         # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies using pnpm
      - name: Install dependencies
        run: npm install

      # Build the container
      - name: Build container
        run: npm run build

      # Define AWS CLI
      - name: Set up AWS CLI
        uses: shinyinc/action-aws-cli@v1.2
        

      # Deploy the container to S3 bucket
      - name: Deploy to S3
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
